# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/feliks/Vivado/AutoCorrelationFunction/AutoCorrelationFunction.srcs/sources_1/ip/blk_mem_gen_full_acf/blk_mem_gen_full_acf.xci
# IP: The module: 'blk_mem_gen_full_acf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/feliks/Vivado/AutoCorrelationFunction/AutoCorrelationFunction.srcs/sources_1/ip/blk_mem_gen_full_acf/blk_mem_gen_full_acf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_full_acf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/feliks/Vivado/AutoCorrelationFunction/AutoCorrelationFunction.srcs/sources_1/ip/blk_mem_gen_full_acf/blk_mem_gen_full_acf.xci
# IP: The module: 'blk_mem_gen_full_acf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/feliks/Vivado/AutoCorrelationFunction/AutoCorrelationFunction.srcs/sources_1/ip/blk_mem_gen_full_acf/blk_mem_gen_full_acf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_full_acf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
