# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Vitis/Vivado/custom_ip_repo/Autocorrelation-Function-AXI/AutoCorrelationFunction.srcs/sources_1/ip/dual_port_acf_bram/dual_port_acf_bram.xci
# IP: The module: 'dual_port_acf_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vitis/Vivado/custom_ip_repo/Autocorrelation-Function-AXI/AutoCorrelationFunction.srcs/sources_1/ip/dual_port_acf_bram/dual_port_acf_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_port_acf_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Vitis/Vivado/custom_ip_repo/Autocorrelation-Function-AXI/AutoCorrelationFunction.srcs/sources_1/ip/dual_port_acf_bram/dual_port_acf_bram.xci
# IP: The module: 'dual_port_acf_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vitis/Vivado/custom_ip_repo/Autocorrelation-Function-AXI/AutoCorrelationFunction.srcs/sources_1/ip/dual_port_acf_bram/dual_port_acf_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_port_acf_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
